{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "generic-webhook.serviceAccountName" . }}
  labels:
    {{- include "generic-webhook.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "generic-webhook.serviceAccountName" . }}"
rules:
{{- with .Values.serviceAccount.roleRules }}
  {{- toYaml . | nindent 0 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: "{{ include "generic-webhook.serviceAccountName" . }}"
subjects:
- kind: ServiceAccount
  name: "{{ include "generic-webhook.serviceAccountName" . }}"
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: "{{ include "generic-webhook.serviceAccountName" . }}"
  apiGroup: rbac.authorization.k8s.io
{{- end }}
